#!/usr/bin/env bash

# File paths
SETTINGS_FILE="$HOME/.config/hypr/settings.json"
WEATHER_SCRIPT="$(dirname "$0")/weather.sh"
ENV_FILE="$(dirname "$0")/quickshell/calendar/.env"

# Target configuration files based on the modular structure
CONF_DIR="$HOME/.config/hypr/config"
SETTINGS_CONF="$CONF_DIR/settings.conf"
AUTOSTART_CONF="$CONF_DIR/autostart.conf"
ENV_CONF="$CONF_DIR/env.conf"
KEYBINDS_CONF="$CONF_DIR/keybindings.conf"
MONITORS_CONF="$CONF_DIR/monitors.conf"

ZSH_RC="$HOME/.zshrc"

# Ensure the required files and directories exist before watching
mkdir -p "$(dirname "$SETTINGS_FILE")"
mkdir -p "$(dirname "$ENV_FILE")"
mkdir -p "$CONF_DIR"
[ ! -f "$SETTINGS_FILE" ] && echo "{}" > "$SETTINGS_FILE"

# Define cache directory for state tracking
CACHE_DIR="$HOME/.cache/settings_watcher"
mkdir -p "$CACHE_DIR"

echo "Started watching settings directories for changes..."

inotifywait -m -q -e close_write,moved_to --format '%w%f' "$(dirname "$SETTINGS_FILE")" "$(dirname "$ENV_FILE")" | while read -r filepath; do
    
    # ---------------------------------------------------------
    # SETTINGS JSON TRIGGER
    # ---------------------------------------------------------
    if [[ "$filepath" == "$SETTINGS_FILE" ]]; then
        echo "Settings file modified. Checking for specific changes..."

        # 1. Capture current states as compact JSON strings
        NEW_GENERAL=$(jq -c '{language, kbOptions, openGuideAtStartup, wallpaperDir}' "$SETTINGS_FILE" 2>/dev/null)
        NEW_KEYBINDS=$(jq -c '.keybinds' "$SETTINGS_FILE" 2>/dev/null)
        NEW_MONITORS=$(jq -c '.monitors' "$SETTINGS_FILE" 2>/dev/null)

        # 2. Update General Settings if changed
        if [[ "$NEW_GENERAL" != "$(cat "$CACHE_DIR/general" 2>/dev/null)" ]]; then
            echo "General settings changed. Applying..."
            
            LANG=$(jq -r '.language // empty' "$SETTINGS_FILE")
            KB_OPT=$(jq -r '.kbOptions // empty' "$SETTINGS_FILE")
            GUIDE_STARTUP=$(jq -r '.openGuideAtStartup' "$SETTINGS_FILE")
            WP_DIR=$(jq -r '.wallpaperDir // empty' "$SETTINGS_FILE")

            [ -n "$LANG" ] && [ "$LANG" != "null" ] && sed -i "s/^ *kb_layout =.*/    kb_layout = $LANG/" "$SETTINGS_CONF"
            
            if [ -n "$KB_OPT" ] && [ "$KB_OPT" != "null" ]; then
                sed -i "s/^ *kb_options =.*/    kb_options = $KB_OPT/" "$SETTINGS_CONF"
            else
                sed -i "s/^ *kb_options =.*/    kb_options = /" "$SETTINGS_CONF"
            fi

            if [ "$GUIDE_STARTUP" == "true" ]; then
                sed -i 's|^#*[[:space:]]*exec-once = ~/.config/hypr/scripts/qs_manager.sh toggle guide.*|exec-once = ~/.config/hypr/scripts/qs_manager.sh toggle guide \&|' "$AUTOSTART_CONF"
            elif [ "$GUIDE_STARTUP" == "false" ]; then
                sed -i 's|^exec-once = ~/.config/hypr/scripts/qs_manager.sh toggle guide.*|# exec-once = ~/.config/hypr/scripts/qs_manager.sh toggle guide \&|' "$AUTOSTART_CONF"
            fi

            if [ -n "$WP_DIR" ] && [ "$WP_DIR" != "null" ]; then
                sed -i "s|^env = WALLPAPER_DIR,.*|env = WALLPAPER_DIR,$WP_DIR|" "$ENV_CONF"
                [ -f "$ZSH_RC" ] && sed -i "s|^export WALLPAPER_DIR=.*|export WALLPAPER_DIR=\"$WP_DIR\"|" "$ZSH_RC"
            fi
            
            echo "$NEW_GENERAL" > "$CACHE_DIR/general"
        fi

        # 3. Update Keybindings if changed
        if [[ "$NEW_KEYBINDS" != "$(cat "$CACHE_DIR/keybinds" 2>/dev/null)" ]]; then
            echo "Keybinds changed. Regenerating..."
            cat << 'EOF' > "$KEYBINDS_CONF"
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ KEYBINDINGS (Auto-generated by Quickshell Settings Watcher)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# ───────── Mouse & Gestures ─────────
gesture = 3, horizontal, workspace

# ───────── Dynamic Keybinds ─────────
EOF
            jq -r '.keybinds[]? | "\(.type // "bind") = \(.mods // ""), \(.key // ""), \(.dispatcher // "exec")\(if .command and .command != "" then ", \(.command)" else "" end)"' "$SETTINGS_FILE" >> "$KEYBINDS_CONF"
            echo "$NEW_KEYBINDS" > "$CACHE_DIR/keybinds"
        fi

        # 4. Update Monitors if changed
        if [[ "$NEW_MONITORS" != "$(cat "$CACHE_DIR/monitors" 2>/dev/null)" ]]; then
            echo "Monitors changed. Regenerating..."
            cat << 'EOF' > "$MONITORS_CONF"
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MONITORS (Auto-generated by Quickshell Settings Watcher)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF
            MONITOR_COUNT=$(jq '.monitors | length' "$SETTINGS_FILE" 2>/dev/null)
            if [[ "$MONITOR_COUNT" -gt 0 ]]; then
                jq -r '.monitors[]? | "monitor = \(.name), \(.resW)x\(.resH)@\(.rate), \(.x)x\(.y), \(.scale)\(if .transform and .transform != 0 then ", transform, \(.transform)" else "" end)"' "$SETTINGS_FILE" >> "$MONITORS_CONF"
            else
                echo "monitor = , preferred, auto, 1" >> "$MONITORS_CONF"
            fi
            echo "$NEW_MONITORS" > "$CACHE_DIR/monitors"
        fi

    # ---------------------------------------------------------
    # .ENV WEATHER TRIGGER
    # ---------------------------------------------------------
    elif [[ "$filepath" == "$ENV_FILE" ]]; then
        echo ".env updated! Forcing weather cache refresh..."
        if [ -x "$WEATHER_SCRIPT" ]; then
            "$WEATHER_SCRIPT" --getdata &
        else
            bash "$WEATHER_SCRIPT" --getdata &
        fi
    fi
done
