# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ AUTOSTART
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

exec-once = systemctl --user start hyprpolkitagent
exec-once = awww-daemon
exec-once = hypridle
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/Main.qml
exec-once = quickshell -p ~/.config/hypr/scripts/quickshell/TopBar.qml
exec-once = python3 ~/.config/hypr/scripts/quickshell/focustime/focus_daemon.py &
exec-once = ~/.config/hypr/scripts/init.sh
exec-once = ~/.config/hypr/scripts/settings_watcher.sh &
exec-once = ~/.config/hypr/scripts/qs_manager.sh toggle guide & 
exec-once = playerctld
exec-once = swayosd-server --top-margin 0.9 --style "$HOME/.config/swayosd/style.css"
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = ~/.config/hypr/scripts/volume_listener.sh
exec-once = ~/.config/hypr/scripts/update_notifier.sh
